#!/bin/sh
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
IGreen='\033[0;92m'
Yellow='\033[0;33m'
IYellow='\033[0;93m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
White='\033[0;37m'
clear='\033[0m'
checks() 
{
if [[ -e $HOME/.sca.txt ]]
then
echo -e "[${Green}✔${clear}] ${IGreen}Checking...${clear}"
echo -e "[${Green}✔${clear}] ${IGreen}Router address found..${clear}"
else
echo -e "[${Green}✔${clear}] ${IGreen}Router address not found...${clear}"
echo -en "[${Green}✔${clear}] ${IGreen}Enter your router address: ${clear}"
read rou
saved=$(echo -e "$rou")
echo -e "$saved" >$HOME/.sca.txt
fi
}
checks
scanss()
{
spec=$(cat $HOME/.sca.txt)
nmap -sn -PE -R -v $spec/24|grep -B1 "Host is up"|grep "Nmap scan report for"|sed 's#Nmap scan report for#Device found 🖥️├───#g;s#)##g;s#(##g;s#_gateway#Router#g'|awk '{print "\033[0;31m"$1" "$2":\033[0m",""$3" "$4" "$5" "$6}'
}

scanss 2>/dev/null
