#!/bin/bash
sshaa()
{
if command -v ssh &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

javaaa()
{
if command -v java &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

nmapaa()
{
if command -v nmap &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

jqaa()
{
if command -v jq &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

pvaa()
{
if command -v pv &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

vimaa()
{
if command -v vim &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

ncataa()
{
if command -v ncat &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

wgeto()
{
if command -v wget &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

meta()
{
if command -v msfconsole &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

curlo()
{
if command -v curl &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

phpto()
{
if command -v php &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

zipp()
{
if command -v zip &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

unzipp()
{
if command -v unzip &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

apktoolo()
{
if command -v apktool &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

apksignero()
{
if command -v apksigner &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

zipppaa()
{
if command -v zipalign &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

sslaa()
{
if command -v openssl &>/dev/null; then
  echo "[✅️] Installed"
else
  echo "[❌️] Not-installed"
fi
}

echo "[ -PLEASE SATISFY THE REQUIREMENTS LISTED BELOW- ]"

meta|sed 's#^#\tMetasploit is \t- #g'
ncataa|sed 's#^#\tNcat is \t- #g'
curlo|sed 's#^#\tCurl is \t- #g'
wgeto|sed 's#^#\tWget is \t- #g'
phpto|sed 's#^#\tPhp is \t\t- #g'
zipp|sed 's#^#\tZip is \t\t- #g'
unzipp|sed 's#^#\tUnzip is \t- #g'
apktoolo|sed 's#^#\tApktool is \t- #g'
apksignero|sed 's#^#\tApksigner is \t- #g'
javaaa|sed 's#^#\tJava17 is \t- #g'
pvaa|sed 's#^#\tPv is \t\t- #g'
vimaa|sed 's#^#\tVim is \t\t- #g'
sshaa|sed 's#^#\tSSH is \t\t- #g'
jqaa|sed 's#^#\tJq is \t\t- #g'
zipppaa|sed 's#^#\tZipalign is \t- #g'
sslaa|sed 's#^#\tOpenssl is \t- #g'
