#!/data/data/com.termux/files/usr/bin/bash

list_colors() {
cat << EOF
Pink:
LightPink:
HotPink:
DeepPink:
PaleVioletRed:
MediumVioletRed:
LightSalmon:
Salmon:
DarkSalmon:
LightCoral:
IndianRed:
Crimson:
FireBrick:
DarkRed:
Red:
OrangeRed:
Tomato:
Coral:
DarkOrange:
Orange:
Gold:
Yellow:
LightYellow:
LemonChiffon:
LightGoldenrodYellow:
PapayaWhip:
Moccasin:
PeachPuff:
PaleGoldenrod:
Khaki:
DarkKhaki:
Lavender:
Thistle:
Plum:
Violet:
Orchid:
Fuchsia:
Magenta:
MediumOrchid:
MediumPurple:
BlueViolet:
DarkViolet:
DarkOrchid:
DarkMagenta:
Purple:
Indigo:
SlateBlue:
DarkSlateBlue:
MediumSlateBlue:
GreenYellow:
Chartreuse:
LawnGreen:
Lime:
LimeGreen:
PaleGreen:
LightGreen:
MediumSpringGreen:
SpringGreen:
MediumSeaGreen:
SeaGreen:
ForestGreen:
Green:
DarkGreen:
YellowGreen:
OliveDrab:
Olive:
DarkOliveGreen:
MediumAquamarine:
DarkSeaGreen:
LightSeaGreen:
DarkCyan:
Teal:
Aqua:
Cyan:
LightCyan:
PaleTurquoise:
Aquamarine:
Turquoise:
MediumTurquoise:
DarkTurquoise:
CadetBlue:
SteelBlue:
LightSteelBlue:
PowderBlue:
LightBlue:
SkyBlue:
LightSkyBlue:
DeepSkyBlue:
DodgerBlue:
CornflowerBlue:
RoyalBlue:
Blue:
MediumBlue:
DarkBlue:
Navy:
MidnightBlue:
Brown:
Maroon:
SaddleBrown:
Sienna:
Chocolate:
Peru:
SandyBrown:
BurlyWood:
Tan:
RosyBrown:
MistyRose:
LightGray:
Silver:
DarkGray:
Gray:
DimGray:
Black:
White:
EOF
}


show_help() {
    echo -e "\nAvailable Colors:"
    list_colors | cut -d':' -f1 | xargs -n5
    echo
}


if [[ "$1" == "-h" || "$1" == "--h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi


if [[ -z "$1" ]]; then
    echo "Error: No color name provided. Use -h for help."
    exit 1
fi


color_hex=$(list_colors | grep -i "^$1:" | cut -d':' -f2)


if [[ -z "$color_hex" ]]; then
    echo "Error: Invalid color name '$1'. Use -h to see available options."
    exit 1
fi


config_file="$HOME/.termux/colors.properties"


mkdir -p "$HOME/.termux"
touch "$config_file"


if grep -q "^foreground=" "$config_file"; then
    sed -i "s/^foreground=.*/foreground=$color_hex/" "$config_file"
else
    echo "foreground=$color_hex" >> "$config_file"
fi


if command -v termux-reload-settings >/dev/null 2>&1; then
    termux-reload-settings
    echo "Foreground color changed to $1 ($color_hex)"
else
    echo "Foreground color updated to $color_hex."
    echo "Note: 'termux-reload-settings' not found."
fi
