#!/data/data/com.termux/files/usr/bin/bash

list_colors() {
cat << EOF
Pink:#FFC0CB
LightPink:#FFB6C1
HotPink:#FF69B4
DeepPink:#FF1493
PaleVioletRed:#DB7093
MediumVioletRed:#C71585
LightSalmon:#FFA07A
Salmon:#FA8072
DarkSalmon:#E9967A
LightCoral:#F08080
IndianRed:#CD5C5C
Crimson:#DC143C
FireBrick:#B22222
DarkRed:#8B0000
Red:#FF0000
OrangeRed:#FF4500
Tomato:#FF6347
Coral:#FF7F50
DarkOrange:#FF8C00
Orange:#FFA500
Gold:#FFD700
Yellow:#FFFF00
LightYellow:#FFFFE0
LemonChiffon:#FFFACD
LightGoldenrodYellow:#FAFAD2
PapayaWhip:#FFEFD5
Moccasin:#FFE4B5
PeachPuff:#FFDAB9
PaleGoldenrod:#EEE8AA
Khaki:#F0E68C
DarkKhaki:#BDB76B
Lavender:#E6E6FA
Thistle:#D8BFD8
Plum:#DDA0DD
Violet:#EE82EE
Orchid:#DA70D6
Fuchsia:#FF00FF
Magenta:#FF00FF
MediumOrchid:#BA55D3
MediumPurple:#9370DB
BlueViolet:#8A2BE2
DarkViolet:#9400D3
DarkOrchid:#9932CC
DarkMagenta:#8B008B
Purple:#800080
Indigo:#4B0082
SlateBlue:#6A5ACD
DarkSlateBlue:#483D8B
MediumSlateBlue:#7B68EE
GreenYellow:#ADFF2F
Chartreuse:#7FFF00
LawnGreen:#7CFC00
Lime:#00FF00
LimeGreen:#32CD32
PaleGreen:#98FB98
LightGreen:#90EE90
MediumSpringGreen:#00FA9A
SpringGreen:#00FF7F
MediumSeaGreen:#3CB371
SeaGreen:#2E8B57
ForestGreen:#228B22
Green:#008000
DarkGreen:#006400
YellowGreen:#9ACD32
OliveDrab:#6B8E23
Olive:#808000
DarkOliveGreen:#556B2F
MediumAquamarine:#66CDAA
DarkSeaGreen:#8FBC8F
LightSeaGreen:#20B2AA
DarkCyan:#008B8B
Teal:#008080
Aqua:#00FFFF
Cyan:#00FFFF
LightCyan:#E0FFFF
PaleTurquoise:#AFEEEE
Aquamarine:#7FFFD4
Turquoise:#40E0D0
MediumTurquoise:#48D1CC
DarkTurquoise:#00CED1
CadetBlue:#5F9EA0
SteelBlue:#4682B4
LightSteelBlue:#B0C4DE
PowderBlue:#B0E0E6
LightBlue:#ADD8E6
SkyBlue:#87CEEB
LightSkyBlue:#87CEFA
DeepSkyBlue:#00BFFF
DodgerBlue:#1E90FF
CornflowerBlue:#6495ED
RoyalBlue:#4169E1
Blue:#0000FF
MediumBlue:#0000CD
DarkBlue:#00008B
Navy:#000080
MidnightBlue:#191970
Brown:#A52A2A
Maroon:#800000
SaddleBrown:#8B4513
Sienna:#A0522D
Chocolate:#D2691E
Peru:#CD853F
SandyBrown:#F4A460
BurlyWood:#DEB887
Tan:#D2B48C
RosyBrown:#BC8F8F
MistyRose:#FFE4E1
LightGray:#D3D3D3
Silver:#C0C0C0
DarkGray:#A9A9A9
Gray:#808080
DimGray:#696969
Black:#000000
White:#FFFFFF
EOF
}

show_help() {
    echo -e "\nAvailable Colors:"
    list_colors | cut -d':' -f1 | xargs -n5
    echo
}

if [[ "$1" == "-h" || "$1" == "--h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

if [[ -z "$1" ]]; then
    echo "Error: No color name provided. Use -h for help."
    exit 1
fi

color_hex=$(list_colors | grep -i "^$1:" | cut -d':' -f2)

if [[ -z "$color_hex" ]]; then
    echo "Error: Invalid color name '$1'. Use -h to see available options."
    exit 1
fi

config_file="$HOME/.termux/colors.properties"

mkdir -p "$HOME/.termux"
touch "$config_file"

if grep -q "^foreground=" "$config_file"; then
    sed -i "s/^foreground=.*/foreground=$color_hex/" "$config_file"
else
    echo "foreground=$color_hex" >> "$config_file"
fi

if command -v termux-reload-settings >/dev/null 2>&1; then
    termux-reload-settings
    echo "Foreground color changed to $1 ($color_hex)"
else
    echo "Foreground color updated to $color_hex."
    echo "Note: 'termux-reload-settings' not found."
fi
