#!/bin/bash
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
IGreen='\033[0;92m'
Yellow='\033[0;33m'
IYellow='\033[0;93m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
White='\033[0;37m'
clear='\033[0m'
pkill ngrok
tcpip(){
echo -en "$Green \b[$IGreen \bENTER$Green \b]$Cyan LPORT$Green  :$IYellow "
read lps
$HOME/ngrok tcp $lps > /dev/null &
sleep 7

ipo=$(curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url|sed 's#tcp://##g'|sed 's#:# #g'|awk '{print $1}')
ip=$(host $ipo|awk '{print $NF}') 
vport=$(curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url|sed 's#tcp://##g'|sed 's#:# #g'|awk '{print $2}')
}
tcpip
echo -e "$Green \b[$IGreen \bOK$Green \b]$Cyan LPORT$Green     =$IYellow $lps"
echo -e "$Green \b[$IGreen \bOK$Green \b]$Cyan IP$Green        =$IYellow $ip"
echo -e "$Green \b[$IGreen \bOK$Green \b]$Cyan VPORT$Green     =$IYellow $vport"
sleep 0.9
sleep 0.9
